# Code generated by SdkContractGenerator. DO NOT EDIT.

CONTRACT = {
    "text-to-video": {
        "models": ["seedance-1.5-pro", "seedance-2.0", "seedance-2.0-fast", "seedance-v1-lite", "seedance-v1-pro", "seedance-v1-pro-fast"],
        "fields_by_model": {
            "seedance-1.5-pro": {
                "aspect_ratio": {
                    "enum": ["1:1", "4:3", "3:4", "16:9", "9:16", "21:9"]
                },
                "duration_seconds": {
                    "required": True,
                    "min": 4,
                    "max": 12,
                    "type": "integer"
                },
                "output_resolution": {
                    "enum": ["480p", "720p", "1080p"]
                },
                "seed": {
                    "type": "integer"
                }
            },
            "seedance-2.0": {
                "aspect_ratio": {
                    "enum": ["1:1", "4:3", "3:4", "16:9", "9:16", "21:9", "auto"]
                },
                "duration_seconds": {
                    "min": 4,
                    "max": 15,
                    "type": "integer"
                },
                "output_resolution": {
                    "enum": ["480p", "720p", "1080p"]
                },
                "seed": {
                    "type": "integer"
                }
            },
            "seedance-2.0-fast": {
                "aspect_ratio": {
                    "enum": ["1:1", "4:3", "3:4", "16:9", "9:16", "21:9", "auto"]
                },
                "duration_seconds": {
                    "min": 4,
                    "max": 15,
                    "type": "integer"
                },
                "output_resolution": {
                    "enum": ["480p", "720p"]
                },
                "seed": {
                    "type": "integer"
                }
            },
            "seedance-v1-lite": {
                "aspect_ratio": {
                    "enum": ["1:1", "4:3", "3:4", "16:9", "9:16", "9:21"]
                },
                "duration_seconds": {
                    "enum": [5, 10],
                    "required": True,
                    "type": "integer"
                },
                "output_resolution": {
                    "enum": ["480p", "720p", "1080p"]
                },
                "seed": {
                    "type": "integer"
                }
            },
            "seedance-v1-pro": {
                "aspect_ratio": {
                    "enum": ["1:1", "4:3", "3:4", "16:9", "9:16", "21:9"]
                },
                "duration_seconds": {
                    "enum": [5, 10],
                    "required": True,
                    "type": "integer"
                },
                "output_resolution": {
                    "enum": ["480p", "720p", "1080p"]
                },
                "seed": {
                    "type": "integer"
                }
            },
            "seedance-v1-pro-fast": {
                "duration_seconds": {
                    "enum": [5, 10],
                    "required": True,
                    "type": "integer"
                },
                "first_frame_image_url": {
                    "required": True
                },
                "output_resolution": {
                    "enum": ["720p", "1080p"]
                },
                "seed": {
                    "type": "integer"
                }
            }
        }
    }
}
